language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: Testing
      script:
        - python3 -m pytest -v tests/test_dice.py
    - stage: Deploy to staging
      script: skip
      deploy:
        provider: heroku
        app: homework-4-ci-cd
        api_key: "$HEROKU_AUTH_TOKEN"
        on:
          all_branches: true
    - stage: Test staging
      script: curl https://homework-4-ci-cd.herokuapp.com/
    - stage: Deploy to production
      script: skip
      deploy:
        provider: heroku
        app: homework-4-ci-cd2
        api_key: "$HEROKU_AUTH_TOKEN"
        on:
          all_branches: true
    - stage: Test production
      script: curl https://homework-4-ci-cd2.herokuapp.com/
notifications:
  slack:
    rooms:
	  - praxisunal:tqZEMhhr054if6W75TF1ZdeY#travis
